version: "3.4"

services:
  clerkapi:
    container_name: clerk-api
    image: ${DOCKER_REGISTRY-}clerkapi
    build:
      context: .
      dockerfile: ClerkApi/Dockerfile
    volumes:
      - "database-volume:/app/App_Data/Database/aidreminder.db"
    ports:
      - "8081:80"
      - "44347:443"

  managerapi:
    container_name: manager-api
    image: ${DOCKER_REGISTRY-}managerapi
    build:
      context: .
      dockerfile: ManagerApi/Dockerfile
    volumes:
      - "database-volume:/app/App_Data/Database/aidreminder.db"
    ports:
      - "8082:80"
      - "44348:443"

volumes:
  database-volume:
