# A docker compose file to start an Artemis AMQP broker
# more details on https://github.com/vromero/activemq-artemis-docker.
version: '2'

services:

  artemis:
    image: vromero/activemq-artemis:2.8.0-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ARTEMIS_USERNAME: quarkus 
      ARTEMIS_PASSWORD: quarkus
  postgres: 
    image: postgres:alpine
    container_name: quartz-db
    volumes:
      - ./init_quartz.sql:/docker-entrypoint-initdb.d/init.sql
      - quartz-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quartz
      - POSTGRES_PASSWORD=quartz
      - POSTGRES_DB=quartz
    ports:
      - 5432:5432
    networks:
      - scheduler-network
networks:
  scheduler-network:
volumes:
  quartz-db:
